export const ADD_ARTIST_SUCCESS = 'ADD_ARTIST_SUCCESS';
export const ADD_ARTIST_FAILURE = 'ADD_ARTIST_FAILURE';
export const ADD_ARTIST_STARTED = 'ADD_ARTIST_STARTED';
export const FETCH_ARTIST_SUCCESS = 'FETCH_ARTIST_SUCCESS';
export const FETCH_ARTIST_STARTED = 'FETCH_ARTIST_STARTED';
export const FETCH_ARTIST_FAILURE = 'FETCH_ARTIST_FAILURE';
export const DELETE_ARTIST_SUCCESS = 'DELETE_ARTIST_SUCCESS';
export const DELETE_ARTIST_FAILURE = 'DELETE_ARTIST_FAILURE';
export const DELETE_ARTIST_STARTED = 'DELETE_ARTIST_STARTED';
export const EDIT_ARTIST = 'EDIT_ARTIST';

export const ADD_ALBUM_SUCCESS = 'ADD_ALBUM_SUCCESS';
export const ADD_ALBUM__FAILURE = 'ADD_ALBUM_FAILURE';
export const ADD_ALBUM__STARTED = 'ADD_ALBUM_STARTED';
export const FETCH_ALBUM_SUCCESS = 'FETCH_ALBUM_SUCCESS';
export const FETCH_ALBUM_FAILURE = 'FETCH_ALBUM_FAILURE';
export const EDIT_ALBUM = 'EDIT_ALBUM ';
export const DELECT_ALBUM_ = 'DELECT_ALBUM';
